---
- name: get haskell/ghc repo key
  apt_key:
    id: BA3CBA3FFE22B574
    state: present

- name: add haskell/ghc repository
  apt_repository:
    repo: deb http://downloads.haskell.org/debian stretch main
    filename: tidal_haskell
    state: present
    validate_certs: yes
    update_cache: yes

- name: install ghc-8.0.2
  apt:
    state: latest
    update_cache: yes
    install_recommends: no
    name: 'ghc-8.0.2'

- name: setup symlinks in /usr/local/bin
  file:
    src: "/opt/ghc/8.0.2/bin/{{ item.src }}"
    dest: "/usr/local/bin/{{ item.dest }}"
    owner: root
    group: root
    state: link
  with_items:
    - { src: ghc-8.0.2, dest: ghc }
    - { src: ghci-8.0.2, dest: ghci }
    - { src: ghc-pkg-8.0.2, dest: ghc-pkg }
    - { src: haddock-ghc-8.0.2, dest: haddock }
    - { src: runghc-8.0.2, dest: runghc }
    - { src: runghc, dest: runhaskell }
    - { src: hp2ps, dest: hp2ps }
    - { src: hpc, dest: hpc }
    - { src: hsc2hs, dest: hsc2hs }

- name: update PATH
  lineinfile:
    path: "/home/{{ansible_env.SUDO_USER}}/.bashrc"
    state: present
    line: PATH=/opt/ghc/bin/:$PATH
  become: yes
  become_method: su
  become_user: "{{ansible_env.SUDO_USER}}"
  become_flags: '-s /bin/bash'

