---
- block:
  - name: create staging/build directory parent ~/.local (if required)
    file:
      path: "/home/{{ansible_env.SUDO_USER}}/.local"
      state: directory
      mode: '0775'

  - name: clone https://github.com/yaxu/feedforward into ~/.local/
    git:
      repo: 'https://github.com/yaxu/feedforward.git'
      dest: "/home/{{ansible_env.SUDO_USER}}/.local/feedforward"

  - name: update cabal
    shell: cabal update  
  
  - name: compile and install c2hs dependency
    shell: cabal install c2hs
    register: c2in
    changed_when: "not c2in.stdout is search('All the requested packages are already installed:')"

  - name: compile and install feedforward editor
    shell: cabal install 
    args:
      chdir: "/home/{{ansible_env.SUDO_USER}}/.local/feedforward"

  become: yes
  become_method: su
  become_user: "{{ansible_env.SUDO_USER}}"
  become_flags: '-s /bin/bash'

- name: set up symlink in /usr/local/bin/feedforward
  file:
    src: "/home/{{ansible_env.SUDO_USER}}/.cabal/bin/feedforward"
    dest: /usr/local/bin/feedforward
    owner: root
    group: root
    state: link

