---
- block:
  - name: create staging/build directory parent ~/.local (if required)
    file:
      path: "/home/{{ansible_env.SUDO_USER}}/.local"
      state: directory
      mode: '0775'

  - name: clone https://github.com/yaxu/feedforward into ~/.local/
    git:
      repo: 'https://github.com/yaxu/feedforward.git'
      dest: "/home/{{ansible_env.SUDO_USER}}/.local/feedforward"
    register: gitup

  - name: check if we have successfully built previously
    stat:
      path:  "/home/{{ansible_env.SUDO_USER}}/.cabal/bin/feedforward"
    register: ffbin

  - block:
    - name: update cabal
      shell: cabal update  
      changed_when: false
    
    - set_fact:
        c2hs_cmd: cabal install c2hs --lib
      when: ansible_distribution_release == "bullseye"

    - set_fact:
        c2hs_cmd: cabal install c2hs
      when: ansible_distribution_release != "bullseye"

    - name: compile and install c2hs dependency
      shell: "{{ c2hs_cmd }}"
      register: c2in
      changed_when: "not c2in.stdout is search('All the requested packages are already installed:')"

    - name: compile and install feedforward editor
      shell: cabal install 
      args:
        chdir: "/home/{{ansible_env.SUDO_USER}}/.local/feedforward"
    when: gitup.changed

  become: yes
  become_method: su
  become_user: "{{ansible_env.SUDO_USER}}"
  become_flags: '-s /bin/bash'
