---
- block:
  - name: clone https://github.com/yaxu/feedforward
    git:
      repo: 'https://github.com/yaxu/feedforward.git'
      dest: /tmp/feedforward

  - name: update cabal
    shell: cabal update  
  
  - name: compile and install c2hs dep
    shell: cabal install c2hs
    register: c2in
    changed_when: "not c2in.stdout is search('All the requested packages are already installed:')"

  - name: install feedforward editor
    shell: cabal install 
    args:
      chdir: /tmp/feedforward/

  - debug:
      msg: "feedforward can be run from ~/.cabal/bin/feedforward"

  become: yes
  become_method: su
  become_user: "{{ansible_env.SUDO_USER}}"
  become_flags: '-s /bin/bash'
