---

- name: set up launcher in /usr/local/bin/feedforward
  template:
    src: templates/feedforward.template
    dest: /usr/local/bin/feedforward
    mode: 0755
    owner: root
    group: root

- include_role:
    name: "roles/ugens-{{ item }}"
  vars:
    editor: "{{ feedforward.editor }}"
  with_items: "{{ sc_ugens }}"
  when: sc_ugens is defined
