---
- name: install feedforward build dependencies
  apt:
    state: latest
    update_cache: yes
    install_recommends: no
    name: 'libncursesw5-dev'

- name: workaround old ghc version issue on debian 9/stretch
  include: 02_debian9_ghc_fix.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int < 10
